name: Run Game

on:
  schedule:
    - cron: '0 18 * * *' # Runs at 18:00 UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tweepy requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run script
      env:
        API_KEY: ${{ secrets.API_KEY }}         # Changed name to match GitHub secrets
        API_SECRET_KEY: ${{ secrets.API_SECRET_KEY }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        GAMES_API_KEY: ${{ secrets.GAMES_API_KEY }}
      run: |
        # Debug step to check if variables are set (will be masked in logs)
        if [ -n "$API_KEY" ]; then echo "API_KEY is set"; else echo "API_KEY is not set"; fi
        if [ -n "$API_SECRET_KEY" ]; then echo "API_SECRET_KEY is set"; else echo "API_SECRET_KEY is not set"; fi
        if [ -n "$ACCESS_TOKEN" ]; then echo "ACCESS_TOKEN is set"; else echo "ACCESS_TOKEN is not set"; fi
        if [ -n "$ACCESS_TOKEN_SECRET" ]; then echo "ACCESS_TOKEN_SECRET is set"; else echo "ACCESS_TOKEN_SECRET is not set"; fi
        if [ -n "$GAMES_API_KEY" ]; then echo "GAMES_API_KEY is set"; else echo "GAMES_API_KEY is not set"; fi
        python main_Game.py
