name: Tweet for games

on:
  schedule:
    # Runs at 12 pm mexico city
    - cron: '0 18 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tweepy requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run script
      env:
        API_KEY: ${{ secrets.PI_KEY }}
        API_SECRET_KEY: ${{ secrets.TWITTER_API_SECRET_KEY }}
        ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        GAMES_API_KEY: ${{ secrets.GAMES_API_KET }} 
      run: python main_Game.py
